services:
  postgres:
    image: postgres
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432 # 本地端口:容器端口
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  # 轻量级Phpmyadmin
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
